name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      TEST_DB_HOST: "postgres_test"
      TEST_DB_DRIVER: "postgres"
      TEST_API_SECRET: "98hbun98h"
      TEST_DB_USER: "encorpluptit"
      TEST_DB_PASSWORD: "password"
      TEST_DB_NAME: "PersonalSpaceDB_test"
      TEST_DB_PORT: "5432"

    steps:
      - uses: actions/checkout@v2

      - name: Run test-api
        run: make api-test

      - name: Run API Tests
        id: run-newman
        uses: anthonyvscode/newman-action@v1
        with:
          collection: api/__postman_tests__/MySpace.postman_collection.json
          reporters: cli

      - name: Output summary to console
        run: echo ${{ steps.run-api-tests.outputs.summary }}

  cd:
    runs-on: ubuntu-latest
    needs: ci
#    env:
#      DB_HOST: "fullstack-postgres"
#      DB_DRIVER: "postgres"
#      API_SECRET: "98hbun98h"
#      DB_USER: "encorpluptit"
#      DB_PASSWORD: "password"
#      DB_NAME: "PersonalSpaceDB"
#      DB_PORT: "5432"

    steps:
      - uses: actions/checkout@v2

      - name: Makefile -> api-start
        run: make

      - name: Makefile -> Fclean
        run: make fclean
